# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

dataset:
  max_seq_len: 4096
  max_num_tokens: 8192
  chat_mode: true
  config_overrides:
    sources:
      train:
      - path: "hg://facebook/fairseq2-lm-gsm8k"
        split: "sft_train"
        weight: 1.0
model:
  name: "llama3_2_1b"
tokenizer:
  name: "llama3_2_1b"
common:
  metric_recorders:
    wandb:
      enabled: False
      project: "fairseq2"
      run_name: "sft_llama3_2_1b_instruct_gsm8k"
regime:
  num_steps: 100000
  checkpoint_every_n_steps: 100
  validate_every_n_steps: 100
  checkpoint_every_n_data_epochs: 100
  keep_last_n_checkpoints: 10
  publish_metrics_every_n_steps: 10
  save_model_only: false
