# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

on:
  workflow_call:
    inputs:
      release_type:
        type: string
        required: true

jobs:
  publish_pt20_s3-linux:
    name: Publish to S3 (pt${{ matrix.torch }}, py${{ matrix.py }}, linux-x86_64, ${{ matrix.variant }})
    strategy:
      matrix:
        torch: ['2.0.1']
        py: ['3.8', '3.9', '3.10', '3.11']
        variant: ['cpu', 'cu117', 'cu118']
      max-parallel: 1
    uses: ./.github/workflows/_publish_s3.yaml
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: ${{ matrix.variant }}
      release_type: ${{ inputs.release_type }}

  publish_pt21_s3-linux:
    name: Publish to S3 (pt${{ matrix.torch }}, py${{ matrix.py }}, linux-x86_64, ${{ matrix.variant }})
    strategy:
      matrix:
        torch: ['2.1.2']
        py: ['3.8', '3.9', '3.10', '3.11']
        variant: ['cpu', 'cu118', 'cu121']
      max-parallel: 1
    uses: ./.github/workflows/_publish_s3.yaml
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: ${{ matrix.variant }}
      release_type: ${{ inputs.release_type }}

  publish_pt22_s3-linux:
    name: Publish to S3 (pt${{ matrix.torch }}, py${{ matrix.py }}, linux-x86_64, ${{ matrix.variant }})
    strategy:
      matrix:
        torch: ['2.2.0']
        py: ['3.8', '3.9', '3.10', '3.11']
        variant: ['cpu', 'cu118', 'cu121']
      max-parallel: 1
    uses: ./.github/workflows/_publish_s3.yaml
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: ${{ matrix.variant }}
      release_type: ${{ inputs.release_type }}

  publish_pypi-linux:
    name: Publish to PyPI (pt${{ matrix.torch }}, py${{ matrix.py }}, linux-x86_64, ${{ matrix.variant }})
    needs:
      - publish_pt20_s3-linux
      - publish_pt21_s3-linux
      - publish_pt22_s3-linux
    if: inputs.release_type == 'stable'
    uses: ./.github/workflows/_publish_pypi.yaml
    strategy:
      matrix:
        torch: ['2.2.0']
        py: ['3.8', '3.9', '3.10', '3.11']
        variant: ['cu121']
      max-parallel: 1
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: ${{ matrix.variant }}

  publish_pypi-macos:
    name: Publish to PyPI (pt${{ matrix.torch }}, py${{ matrix.py }}, macos-arm64)
    needs:
      - publish_pypi-linux
    if: inputs.release_type == 'stable'
    uses: ./.github/workflows/_publish_pypi.yaml
    strategy:
      matrix:
        torch: ['2.2.0']
        py: ['3.8', '3.9', '3.10', '3.11']
      max-parallel: 1
    with:
      os: 'macos'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      arch: 'arm64'

  publish_doc:
    name: Publish documentation
    needs:
      - publish_pypi-linux
      - publish_pypi-macos
    # We can't use `success()` here, see
    # https://github.com/orgs/community/discussions/45058.
    if: ${{ !failure() && !cancelled() }}
    uses: ./.github/workflows/_publish_doc.yaml
