# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

on:
  workflow_call:
    inputs:
      release_type:
        type: string
        required: true

jobs:
  publish_pt27_s3-linux:
    name: Publish to S3 (pt${{ matrix.torch }}, py${{ matrix.py }}, linux-x86_64, ${{ matrix.variant }})
    strategy:
      matrix:
        torch: ['2.7.1']
        py: ['3.10', '3.11', '3.12']
        variant: ['cpu', 'cu126', 'cu128']
      max-parallel: 1
    uses: ./.github/workflows/_publish_s3.yaml
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: ${{ matrix.variant }}
      release_type: ${{ inputs.release_type }}

  publish_pt28_s3-linux:
    name: Publish to S3 (pt${{ matrix.torch }}, py${{ matrix.py }}, linux-x86_64, ${{ matrix.variant }})
    strategy:
      matrix:
        torch: ['2.8.0']
        py: ['3.10', '3.11', '3.12']
        variant: ['cpu', 'cu126', 'cu128']
      max-parallel: 1
    uses: ./.github/workflows/_publish_s3.yaml
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: ${{ matrix.variant }}
      release_type: ${{ inputs.release_type }}

  publish_pt29_s3-linux:
    name: Publish to S3 (pt${{ matrix.torch }}, py${{ matrix.py }}, linux-x86_64, ${{ matrix.variant }})
    strategy:
      matrix:
        torch: ['2.9.1']
        py: ['3.10', '3.11', '3.12']
        variant: ['cpu', 'cu126', 'cu128']
      max-parallel: 1
    uses: ./.github/workflows/_publish_s3.yaml
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: ${{ matrix.variant }}
      release_type: ${{ inputs.release_type }}

  publish_pt29_s3-macos:
    name: Publish to S3 (pt${{ matrix.torch }}, py${{ matrix.py }}, macos-arm64)
    strategy:
      matrix:
        torch: ['2.9.1']
        py: ['3.10', '3.11', '3.12']
      max-parallel: 1
    uses: ./.github/workflows/_publish_s3.yaml
    with:
      os: 'macos'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: 'cpu'
      release_type: ${{ inputs.release_type }}
      arch: 'arm64'

  publish_pypi-linux:
    name: Publish to PyPI (pt${{ matrix.torch }}, py${{ matrix.py }}, linux-x86_64, ${{ matrix.variant }})
    needs:
      - publish_pt27_s3-linux
      - publish_pt28_s3-linux
      - publish_pt29_s3-linux
      - publish_pt29_s3-macos
    if: inputs.release_type == 'stable'
    uses: ./.github/workflows/_publish_pypi.yaml
    strategy:
      matrix:
        torch: ['2.9.1']
        py: ['3.10', '3.11', '3.12']
        # Only the variant that corresponds to the PyPI PyTorch package must be
        # included here. NEVER specify more than one variant as that will cause
        # a broken release that can't be rolled back.
        variant: ['cu128']
      max-parallel: 1
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      variant: ${{ matrix.variant }}

  publish_pypi-macos:
    name: Publish to PyPI (pt${{ matrix.torch }}, py${{ matrix.py }}, macos-arm64)
    needs:
      - publish_pypi-linux
    if: inputs.release_type == 'stable'
    uses: ./.github/workflows/_publish_pypi.yaml
    strategy:
      matrix:
        torch: ['2.9.1']
        py: ['3.10', '3.11', '3.12']
      max-parallel: 1
    with:
      os: 'macos'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      arch: 'arm64'

  publish_doc:
    name: Publish documentation
    needs:
      - publish_pypi-linux
      - publish_pypi-macos
    # We can't use `success()` here, see
    # https://github.com/orgs/community/discussions/45058.
    if: ${{ !failure() && !cancelled() }}
    uses: ./.github/workflows/_publish_doc.yaml
