# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      torch:
        type: string
        required: true
      py:
        type: string
        required: true
      variant:
        type: string
        default: 'cpu'
      arch:
        type: string
        default: 'x86_64'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      # Needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
    steps:
      - name: Download wheels from staging
        uses: actions/download-artifact@v3
        with:
          name: pypi-pt${{ inputs.torch }}-py${{ inputs.py }}-${{ inputs.os }}_${{ inputs.arch }}-${{ inputs.variant }}-nosan
          path: artifacts/
      - name: Publish fairseq2n
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            packages-dir: artifacts/native/python/build/wheelhouse
      - name: Publish fairseq2
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            packages-dir: artifacts/build/wheelhouse
            # Multiple build variants will attempt to publish the same fairseq2
            # package. Ignore all but the first one.
            skip-existing: true
